import type { Product } from "../types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Кросівки Nike Air Max",
    price: 2499,
    originalPrice: 2999,
    image: "/images/products/nike-air-max.jpg",
    images: ["/images/products/nike-air-max.jpg"],
    description: "Комфортні кросівки для щоденного носіння",
    category: "Кросівки",
    brand: "Nike",
    sizes: [
      { size: "39", stock: 5 },
      { size: "40", stock: 8 },
      { size: "41", stock: 12 },
      { size: "42", stock: 3 },
      { size: "43", stock: 0 },
      { size: "44", stock: 7 },
    ],
    colors: ["Чорний", "Білий", "Сірий"],
    inStock: true,
    stockQuantity: 15,
    rating: 4.5,
    reviewCount: 128,
    features: ["Повітряна подушка", "Легкість", "Зносостійкість"],
    material: "Шкіра",
    releaseYear: 2024,
    country: "Вʼєтнам",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Кросівки Adidas Ultraboost",
    price: 3299,
    image: "/images/products/adidas-ultraboost.jpg",
    images: ["/images/products/adidas-ultraboost.jpg"],
    description: "Технологічні кросівки для бігу",
    category: "Кросівки",
    brand: "Adidas",
    sizes: [
      { size: "39", stock: 5 },
      { size: "40", stock: 8 },
      { size: "41", stock: 12 },
      { size: "42", stock: 3 },
      { size: "43", stock: 0 },
      { size: "44", stock: 7 },
    ],
    colors: ["Чорний", "Білий", "Синій"],
    inStock: true,
    stockQuantity: 8,
    rating: 4.8,
    reviewCount: 95,
    features: ["Технологія Boost", "Енергоповернення", "Адаптивна підошва"],
    material: "Сітка",
    releaseYear: 2024,
    country: "Китай",
    createdAt: "2024-02-10",
  },
  {
    id: "3",
    name: "Черевики Timberland",
    price: 4599,
    image: "/images/products/timberland.jpg",
    images: ["/images/products/timberland.jpg"],
    description: "Міцні черевики для активного відпочинку",
    category: "Черевики",
    brand: "Timberland",
    sizes: [
      { size: "39", stock: 5 },
      { size: "40", stock: 8 },
      { size: "41", stock: 12 },
      { size: "42", stock: 3 },
      { size: "43", stock: 0 },
      { size: "44", stock: 7 },
    ],
    colors: ["Коричневий", "Чорний"],
    inStock: true,
    stockQuantity: 5,
    rating: 4.6,
    reviewCount: 67,
    features: ["Водостійкість", "Міцні матеріали", "Комфорт"],
    material: "Шкіра",
    releaseYear: 2023,
    country: "Домініканська Республіка",
    createdAt: "2023-11-20",
  },
];

reviews: [
  {
    id: "1",
    productId: "1",
    userId: "user1",
    userName: "Андрій",
    rating: 5,
    comment: "Дуже зручні кросівки, носяться вже півроку - все чудово!",
    createdAt: "2024-01-20",
    likes: 12,
    dislikes: 1,
  },
  {
    id: "2",
    productId: "1",
    userId: "user2",
    userName: "Марія",
    rating: 4,
    comment:
      "Якість хороша, але трохи малі на розмір. Беріть на розмір більше.",
    createdAt: "2024-02-15",
    likes: 8,
    dislikes: 0,
  },
];
